#!/bin/sh
#

COVERAGE_THRESHOLD=70

evalute_module_csv() {
	INPUT=$1

	[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 1; }

	i=1
	while IFS=, read group package class instruction_missed instruction_covered branch_missed branch_covered line_missed line_covered complexity_missed complexity_covered method_missed method_covered
	do
		test $i -eq 1 && ((i=i+1)) && continue

		slash=/
		package=${package//./$slash}

		[[ "${class}" =~ [^a-zA-Z] ]] && continue

		if [[ $line_covered -eq 0 ]]
		then
		    #echo "There is no test run for $class in $package"
		    no_test_file="$no_test_file\n$package/$class" # TODO verify names
		else
			line_total=$(($line_covered + $line_missed))
			cov_perc=$(($line_covered*100/$line_total))
			#echo "$line_covered out of $line_total lines (coverage: $cov_perc) are tested at $class in $package"

			if [[ $cov_perc -lt $COVERAGE_THRESHOLD ]]  ;then
				tests_with_low_cov="$tests_with_low_cov\n$package/$class"
			fi
		fi
	done < $INPUT
}


rm -rf ./app/build/covReportDir
rm -rf ./second/build/covReportDir

if ! ./gradlew debugSLKCoverage  ;then
	echo ""
	echo "tests not passed. You are not allowed to push this branch"
	exit 1
fi


tests_with_low_cov=""
no_test_file=""
evalute_module_csv ./app/build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
evalute_module_csv ./second/build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
echo ""

current_branch=$(git symbolic-ref --short HEAD)
added_files=$(git diff --name-only --diff-filter=A origin/$current_branch)
deleted_files=$(git diff --name-only --diff-filter=D origin/$current_branch)
modified_files=$(git diff --name-only --diff-filter=M origin/$current_branch)
script_return=0

echo -e $tests_with_low_cov | while IFS= read -r class
do
  if [[ $class != "" ]]  ;then
	  if [[ $added_files =  *$class* ]] || [[ $modified_files = *$class* ]]  ;then
	  	echo -e "\e[31mPlease improve coverage of $class to be more than $COVERAGE_THRESHOLD\e[0m"
	  	script_return=1 
	  fi
  fi
done

echo -e $no_test_file | while IFS= read -r class  ;do
	if [[ $class != "" ]]  ;then
		if [[ $added_files = *$class* ]] || [[ $deleted_files = *$class* ]]  ;then
			echo -e "\e[31mYou should add unit test for $class with a coverage be more than $COVERAGE_THRESHOLD\e[0m"
			script_return=1
		fi
	fi
done

echo -e "\e[0m "
exit $script_return 

