#!/bin/sh
#

cov_warning=0

evalute_module_csv() {
	INPUT=$1

	[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 1; }

	i=1
	while IFS=, read group package class instruction_missed instruction_covered branch_missed branch_covered line_missed line_covered complexity_missed complexity_covered method_missed method_covered
	do
		test $i -eq 1 && ((i=i+1)) && continue

		if [[ $line_covered -eq 0 ]]
		then
		    echo "There is no test run for $class in $package"
		else
			line_total=$(($line_covered + $line_missed))
			cov_perc=$(($line_covered*100/$line_total))
			echo "$line_covered out of $line_total lines (coverage: $cov_perc) are tested at $class in $package"

			test $cov_perc -lt 60 && ((cov_warning=1))
		fi
	done < $INPUT
}

rm -rf ./app/build/covReportDir
rm -rf ./second/build/covReportDir

if ./gradlew debugSLKCoverage  ;then
	echo ""
else
	echo ""
	echo "tests not passed. You are not allowed to push this branch"
	exit 1
fi


evalute_module_csv ./app/build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
evalute_module_csv ./second/build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
echo ""
echo ""

test $cov_warning -gt 0 && echo "Please improve tests with coverage less than 60" & exit 1


