#!/bin/sh
#

if ./gradlew debugSLKCoverage  ;then
	echo ""
else
	echo ""
	echo "tests not passed. You are not allowed to push this branch"
	exit 1
fi


INPUT=./build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv

[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 1; }

i=1
while IFS=, read group package class instruction_missed instruction_covered branch_missed branch_covered line_missed line_covered complexity_missed complexity_covered method_missed method_covered
do
	test $i -eq 1 && ((i=i+1)) && continue

	if [[ $line_covered -eq 0 ]]
	then
	    echo "There is no test run for $class in $package"
	else
		line_total=$(($line_covered + $line_missed))
	    echo "$line_covered out of $line_total lines are tested at $class in $package"
	fi
done < $INPUT
echo ""
echo ""